version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092, EXTERNAL://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  # producer:
  #   build: ./producer
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - kafka-network

  # consumer:
  #   build: ./consumer
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   networks:
  #     - kafka-network
  #   restart: always

networks:
  kafka-network:
    driver: bridge
